version: "3"
services:
  cpp:
    build: ./cpp
    hostname: wtu-cpp
    volumes:
      - /data/wtu/cpp:/var/wtu/cpp
    restart: always
    container_name: wtu-cpp
    networks:
      - wtu-net
 
networks:
  wtu-net:
    driver: bridge
