FROM ubuntu:latest
LABEL maintainer="chendaye666<chendaye666@gmail.com>"

# ENV TZ "Asia/Shanghai"
# RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# RUN mkdir -p /var/wtu/cpp

# RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
# RUN sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
# RUN apt-get update && apt-get install -y build-essential vim
# RUN apt-get clean